#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.3.5.1 on Wed Dec 01 12:41:42 2004

import wx

class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.main_frame_statusbar = self.CreateStatusBar(1, wx.ST_SIZEGRIP)
        self.radio_box_1_copy = wx.RadioBox(self, -1, _("channels"), choices=[_("mono"), _("stereo")], majorDimension=0, style=wx.RA_SPECIFY_ROWS)
        self.label_frequency = wx.StaticText(self, -1, _("frequency"))
        self.choice_2_copy_copy = wx.Choice(self, -1, choices=[])
        self.label_2 = wx.StaticText(self, -1, _("bit rate"))
        self.choice_3_copy_copy = wx.Choice(self, -1, choices=[])
        self.label_2_copy = wx.StaticText(self, -1, _("input source"))
        self.choice_3_copy_copy_copy = wx.Choice(self, -1, choices=[])
        self.button_start = wx.Button(self, -1, _("start"))
        self.button_stop = wx.Button(self, -1, _("stop"))
        self.button_quit = wx.Button(self, -1, _("quit"))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle(_("MP3 recorder"))
        _icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap("E:\\Documents and Settings\\Administrator\\My Documents\\mp3recorder\\playsound.ico", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.SetBackgroundColour(wx.Colour(226, 226, 135))
        self.main_frame_statusbar.SetStatusWidths([-1])
        # statusbar fields
        main_frame_statusbar_fields = [_("status")]
        for i in range(len(main_frame_statusbar_fields)):
            self.main_frame_statusbar.SetStatusText(main_frame_statusbar_fields[i], i)
        self.radio_box_1_copy.SetBackgroundColour(wx.Colour(226, 226, 135))
        self.radio_box_1_copy.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.radio_box_1_copy.SetSelection(1)
        self.label_frequency.SetBackgroundColour(wx.Colour(226, 226, 135))
        self.label_frequency.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.label_frequency.SetToolTipString(_("Audio input sampling frequency"))
        self.choice_2_copy_copy.SetSelection(0)
        self.label_2.SetBackgroundColour(wx.Colour(226, 226, 135))
        self.label_2.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.label_2.SetToolTipString(_("Bits per second recorded by the mp3 encoder"))
        self.choice_3_copy_copy.SetSelection(0)
        self.label_2_copy.SetBackgroundColour(wx.Colour(226, 226, 135))
        self.label_2_copy.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.label_2_copy.SetToolTipString(_("Where do you want to record audio from"))
        self.choice_3_copy_copy_copy.SetSelection(0)
        self.button_start.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.button_start.SetToolTipString(_("Start recording"))
        self.button_stop.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.button_stop.SetToolTipString(_("Stop recording"))
        self.button_quit.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.button_quit.SetToolTipString(_("Stop recording and quit the application"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        grid_sizer_main_vertical = wx.BoxSizer(wx.VERTICAL)
        sizer_buttonrow_horizontal = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_5_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_main_vertical.Add((20, 20), 0, wx.EXPAND, 0)
        sizer_4.Add((20, 20), 0, wx.EXPAND, 0)
        sizer_4.Add(self.radio_box_1_copy, 1, wx.EXPAND, 0)
        sizer_4.Add((20, 20), 0, wx.EXPAND, 0)
        sizer_3.Add(self.label_frequency, 1, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_3.Add((15, 20), 0, wx.EXPAND, 0)
        sizer_3.Add(self.choice_2_copy_copy, 0, wx.EXPAND, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_2.Add((20, 20), 0, wx.EXPAND, 0)
        sizer_5.Add(self.label_2, 1, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_5.Add((15, 20), 0, wx.EXPAND, 0)
        sizer_5.Add(self.choice_3_copy_copy, 0, wx.EXPAND, 0)
        sizer_2.Add(sizer_5, 1, wx.EXPAND, 0)
        sizer_2.Add((20, 20), 0, wx.EXPAND, 0)
        sizer_5_copy.Add(self.label_2_copy, 1, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_5_copy.Add((15, 20), 0, wx.EXPAND, 0)
        sizer_5_copy.Add(self.choice_3_copy_copy_copy, 0, wx.EXPAND, 0)
        sizer_2.Add(sizer_5_copy, 1, wx.EXPAND, 0)
        sizer_2.Add((20, 20), 0, wx.EXPAND, 0)
        sizer_4.Add(sizer_2, 0, wx.EXPAND, 0)
        sizer_4.Add((20, 20), 0, wx.EXPAND, 0)
        grid_sizer_main_vertical.Add(sizer_4, 1, wx.EXPAND, 0)
        grid_sizer_main_vertical.Add((20, 20), 0, wx.EXPAND, 0)
        sizer_buttonrow_horizontal.Add((15, 20), 8, wx.EXPAND|wx.ALIGN_RIGHT|wx.ALIGN_BOTTOM, 0)
        sizer_buttonrow_horizontal.Add(self.button_start, 0, wx.EXPAND|wx.ALIGN_RIGHT|wx.ALIGN_BOTTOM, 0)
        sizer_buttonrow_horizontal.Add((11, 20), 1, wx.EXPAND|wx.ALIGN_RIGHT|wx.ALIGN_BOTTOM, 0)
        sizer_buttonrow_horizontal.Add(self.button_stop, 0, wx.EXPAND|wx.ALIGN_RIGHT|wx.ALIGN_BOTTOM, 0)
        sizer_buttonrow_horizontal.Add((10, 20), 1, wx.EXPAND|wx.ALIGN_RIGHT|wx.ALIGN_BOTTOM, 0)
        sizer_buttonrow_horizontal.Add(self.button_quit, 0, wx.EXPAND|wx.ALIGN_RIGHT|wx.ALIGN_BOTTOM, 0)
        sizer_buttonrow_horizontal.Add((10, 20), 1, wx.EXPAND|wx.ALIGN_RIGHT|wx.ALIGN_BOTTOM, 0)
        grid_sizer_main_vertical.Add(sizer_buttonrow_horizontal, 0, wx.EXPAND, 0)
        grid_sizer_main_vertical.Add((20, 20), 0, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(grid_sizer_main_vertical)
        grid_sizer_main_vertical.Fit(self)
        grid_sizer_main_vertical.SetSizeHints(self)
        self.Layout()
        # end wxGlade

# end of class MainFrame


if __name__ == "__main__":
    import gettext
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    main_frame = MainFrame(None, -1, "")
    app.SetTopWindow(main_frame)
    main_frame.Show()
    app.MainLoop()
